kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data
  namespace: gitlab
spec:
  storageClassName: openebs-dual-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs
  namespace: gitlab
spec:
  storageClassName: openebs-dual-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: config
  namespace: gitlab
spec:
  storageClassName: openebs-dual-replica
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
